- name: Install base backages
  apt: 
    name: "{{ item }}"
    state: present
  with_items:
    - fail2ban
    - iptables
    - iptables-persistent
    - logwatch
    - sudo

- name: Add {{ main_user }} user with sudo rights.
  user: 
    name: "{{ main_user }}"
    shell: "{{ users_shell }}"
    password: "{{ main_user_password | password_hash('sha512') }}"
    groups: sudo
    append: yes

- name: Add authorized keys for {{ main_user }} user. 
  authorized_key: 
    user: "{{ main_user }}"
    key: "{{ lookup('file', item) }}"
  with_items: "{{ main_user_public_keys }}"

- name: Generate ssh host key (ed25519)
  shell: ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N ""
  args:
    creates: /etc/ssh/ssh_host_ed25519_key

- name: Generate ssh host key (rsa)
  shell: ssh-keygen -t rsa -b 4096 -f /etc/ssh/ssh_host_rsa_key -N ""
  args:
    creates: /etc/ssh/ssh_host_rsa_key

- name: Create sshd configuration file
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: Restart sshd


