- name: Install base backages
  apt: 
    name: "{{ item }}"
    state: present
  with_items:
    - fail2ban
    - iptables
    - iptables-persistent
    - logwatch
    - sudo

- name: Add {{ main_user }} user with sudo rights.
  user: 
    name: "{{ main_user }}"
    shell: "{{ users_shell }}"
    password: "{{ main_user_password | password_hash('sha512') }}"
    groups: sudo
    append: yes

- name: Add authorized keys for {{ main_user }} user. 
  authorized_key: 
    user: "{{ main_user }}"
    key: "{{ lookup('file', item) }}"
  with_items: "{{ main_user_public_keys }}"





